allowBuilds:
  '@parcel/watcher': set this to true or false
  esbuild: set this to true or false
  lmdb: set this to true or false
  msgpackr-extract: set this to true or false
onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - less
  - lmdb
  - msgpackr-extract
