name: Angular CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: |
          npm i -g pnpm
          pnpm install

      - name: Increment version
        if: github.ref == 'refs/heads/master'
        run: |
          cd projects/ngx-monaco-tree
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config user.name "$GITHUB_ACTOR"
          npm version minor -m "v%s"
          VERSION=$(node -p "require('./package.json').version")
          git add package.json
          git commit -m "Bump version to ${VERSION}"
          git tag 'v'${VERSION}
          git push "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"
          git push "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git" --follow-tags
          git push "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git" --tags

      - name: Build project
        run: pnpm run build ngx-monaco-tree

      - name: Publish NPM package
        if: github.ref == 'refs/heads/master'
        run: |
          cd dist/ngx-monaco-tree
          npm publish --access public

        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
